version: 2.1

jobs:
  build:
    
    working_directory: ~/kid-bank

    docker:
      - image: circleci/openjdk:8u131-jdk

    steps:

      - checkout

      - restore_cache:
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: ./mvnw package
      
      - store_test_results:
          path: target/surefire-reports

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
